// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCInW9TiZvRLtM2U3sao__yDynEF7DccGo',
    appId: '1:946743098357:web:a852c9666925c3f7857ebc',
    messagingSenderId: '946743098357',
    projectId: 'e-commerce-62076',
    authDomain: 'e-commerce-62076.firebaseapp.com',
    storageBucket: 'e-commerce-62076.firebasestorage.app',
    measurementId: 'G-56XDX5206T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDjOBsfQLoWFDqVI4Htq6jWL0cixgBSoE',
    appId: '1:946743098357:android:1c55c02651bd8be1857ebc',
    messagingSenderId: '946743098357',
    projectId: 'e-commerce-62076',
    storageBucket: 'e-commerce-62076.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWb6OEjGnjmHoQPMK_wgBT9aok-xykLVg',
    appId: '1:946743098357:ios:e0acb1a340eb8ded857ebc',
    messagingSenderId: '946743098357',
    projectId: 'e-commerce-62076',
    storageBucket: 'e-commerce-62076.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWb6OEjGnjmHoQPMK_wgBT9aok-xykLVg',
    appId: '1:946743098357:ios:e0acb1a340eb8ded857ebc',
    messagingSenderId: '946743098357',
    projectId: 'e-commerce-62076',
    storageBucket: 'e-commerce-62076.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCInW9TiZvRLtM2U3sao__yDynEF7DccGo',
    appId: '1:946743098357:web:0a01ab5fca34b949857ebc',
    messagingSenderId: '946743098357',
    projectId: 'e-commerce-62076',
    authDomain: 'e-commerce-62076.firebaseapp.com',
    storageBucket: 'e-commerce-62076.firebasestorage.app',
    measurementId: 'G-FD8VXF5PHJ',
  );
}
